server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/sanus_db
    username: postgres
    password: rascencio
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        type:
          preferred_boolean_jdbc_type: BOOLEAN
        jdbc:
          type_binding: true
        format_sql: false
logging:
  level:
    org.hibernate.SQL: OFF